# DB Configuration
db:
  url: postgresql://postgres:PASSWORD@localhost:5434/pyverseai

celery:
  broker_url: redis://localhost:6379/0
  celery_result_backend: db+postgresql://postgres:PASSWORD@localhost:5434/pyverseai

socket:
  token: c11c88b85373d33ecf78a18754822935